<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import { mountPublisher } from './'

  import type { AudioOffer, PublishSpec, VideoOffer } from './factory'
  import type { InitPublish } from '..'
  import type { PluginHandle } from 'janus-svelte/plugins/attach'

  // a publish function generated by initialising a janus server
  export let publish: InitPublish

  // what we're offering for video and audio
  export let videoOffer: VideoOffer
  export let audioOffer: AudioOffer

  const dispatch = createEventDispatcher()

  // scoped here so the reactives have access
  let publisher: PluginHandle<PublishSpec>

  // variables that we'll expose to the slot
  let stream: MediaStream
  let feedId: number

  onMount(async () => {
    // create our publisher handle
    publisher = await mountPublisher(publish)

    // when we get a local stream, capture it locally and also dispatch it
    publisher.handle.on('localstream', (handle, s) => {
      stream = s
      dispatch('localstream', s)
    })

    // capture the plugin's ID as the feed ID
    feedId = publisher.plugin.id

    // trigger an attach event
    dispatch('attach', feedId)
  })

  // whenever our video or audio offers change, we want to trigger an offer() in our handle
  $: if (publisher && typeof videoOffer !== 'undefined') { publisher.plugin.offer({ video: videoOffer }) }
  $: if (publisher && typeof audioOffer !== 'undefined') { publisher.plugin.offer({ audio: audioOffer }) }

</script>

{#if stream}
  <slot {stream} {feedId} />
{/if}