<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import { mountPublisher } from './'

  import type { Readable } from 'svelte/store'
  import type { AudioOffer, PublishSpec, VideoOffer } from './factory'
  import type { InitPublish } from '..'
  import type { PluginHandle } from 'janus-svelte/plugins/attach'

  // a publish function generated by initialising a janus server
  export let publish: InitPublish

  // what we're offering for video and audio
  // WARNING: POTENTIAL FOR MEMORY LEAK IF INCORRECTLY USED!
  // Either you should pass a Readable<> *ONCE* and update() it, or pass
  // mutations as direct literals, updated from the parent component. If you
  // pass replacement stores, the subscriptions will leak.
  export let videoOffer: VideoOffer | Readable<VideoOffer>
  export let audioOffer: AudioOffer | Readable<AudioOffer>

  const dispatch = createEventDispatcher()

  // scoped here so the reactives have access
  let publisher: PluginHandle<PublishSpec>

  // variables that we'll expose to the slot
  let stream: MediaStream
  let feedId: number


  // assertion function for testing whether something is a store
  function assertIsStore<T>(offer: any): asserts offer is Readable<T> {
    if (!('subscribe' in offer)) {
      throw new Error('Subscribe method not found')
    }
  }

  onMount(async () => {
    // create our publisher handle
    publisher = await mountPublisher(publish)

    // when we get a local stream, capture it locally and also dispatch it
    publisher.handle.on('localstream', (_, s) => {
      stream = s
      dispatch('localstream', s)
    })

    // capture the plugin's ID as the feed ID
    feedId = publisher.plugin.id

    // trigger an attach event
    dispatch('attach', feedId)
  })

  // whenever our video or audio offers change, we want to trigger an offer() in our handle
  $: if (publisher && typeof videoOffer !== 'undefined') {
    try {
      // is this actually a store?
      assertIsStore<VideoOffer>(videoOffer)
      videoOffer.subscribe(video => publisher.plugin.offer({ video }))

    } catch (e) {
      publisher.plugin.offer({ video: videoOffer as VideoOffer })
    }
  }

  $: if (publisher && typeof audioOffer !== 'undefined') {
    try {
      // is this actually a store?
      assertIsStore<AudioOffer>(audioOffer)
      audioOffer.subscribe(audio => publisher.plugin.offer({ audio }))

    } catch (e) {
      publisher.plugin.offer({ audio: audioOffer as AudioOffer})
    }
  }

</script>

{#if stream}
  <slot {stream} {feedId} />
{/if}
